set -x
./fabcoin-8mb-block.py
./fabcoin-block-header.py
./fabcoin-callcontract.py
./fabcoin-call-empty-contract.py
./fabcoin_cli.py
./fabcoin-combined-outputs-exceed-gas-limit.py
./fabcoin-condensing-txs.py
./fabcoin-createcontract.py
./fabcoin-create-eth-op-code.py
./fabcoin-dgp-block-size-restart.py
./fabcoin-dgp-block-size-sync.py
./fabcoin-dgp-gas-price-lingering-mempool-tx.py
./fabcoin-dgp.py
./fabcoin-evm-globals.py
./fabcoin-gas-limit-overflow.py
./fabcoin-gas-limit.py
./fabcoin-globals-state-changer.py
./fabcoin-identical-refunds.py
./fabcoin-many-value-refunds-from-same-tx.py
./fabcoin-no-exec-call-disabled.py
./fabcoin-null-sender.py
./fabcoin-opcall.py
./fabcoin-opcreate.py
./fabcoin-searchlog.py
./fabcoin-searchlog-restart-node.py
./fabcoin-sendtocontract.py
./fabcoin-soft-block-gas-limits.py
./fabcoin-spend-op-call.py
./fabcoin-state-root.py
./fabcoin-transaction-prioritization.py
./fabcoin-waitforlogs.py
