.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. fabcoin_qt test_fabcoin_qt
clean: FORCE
	$(MAKE) -C .. fabcoin_qt_clean test_fabcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_fabcoin_qt_check
fabcoin-qt fabcoin-qt.exe: FORCE
	 $(MAKE) -C .. fabcoin_qt
